# To access services in two different namespaces you can use url like this:

# HTTP://<your-service-name>.<namespace-with-that-service>.svc.cluster.local
# To list out all your namespaces you can use:

# kubectl get namespace
# And for service in that namespace you can simply use:

# kubectl get services -n <namespace-name>
# Exec into the client.

# kubectl exec deployment/mongo-client -it -- /bin/bash
# Login into the MongoDB shell

# mongo --host mongo-nodeport-svc --port 27017 -u adminuser -p password123
#
#eg. mongo --host mongo-clusterip-svc.mongo.svc.cluster.local --port 27017 -u adminuser -p password123
# kubectl get svc -n <namespace>
# kubectl port-forward service/mongo-clusterip-svc -n mongo 8000:27017
# kubectl port-forward service/<svc-name> -n <namespace> <local-port>:<cluster-port>

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-client
  name: mongo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - image: mongo
        name: mongo-client
        resources:
          limits:
            memory: "2Gi"
            cpu: 500m
          requests:
            memory: "1Gi"
            cpu: 200m        
        env:
        - name: mongo-client_INITDB_ROOT_USERNAME
          value: 'dummy'
        - name: mongo-client_INITDB_ROOT_PASSWORD
          value: 'dummy'
