apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-clusterip-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo